-- Retired: wildcard external tables expose incomplete exports.
-- Native DATE-partitioned serving is provisioned by src/export/export_bigquery.py.
-- Migrate consumers to the environment-specific dataset after reconciliation.
